### ISSUE TITLE
Request - Random Weather Module

### ISSUE THREAD

**Issue by kMaN175** [Malbryn/MalFramework#392]
Would love to see a random weather module added.

**Comment by kMaN175** [comment]
Maybe something like:

Randon Weather Trigger:

Text:
Random Weather

Server Only

Condition:
call{random_weather}

On Activation:
call{0 setOvercast (random [0,0.5,1]);
if (overcast >= 0.9) then { 0 setRain (random [0,0.5,1])};
if (overcast < 0.9) then { 0 setRain (random [0,0,0.0])};
0 setWindForce (random [0,0,1]);
0 setWindStr (random [0,0,1]);
0 setWindDir (random [0,180,360]);
forceWeatherChange;}

**Comment by Malbryn** [comment]
I'm not sure if it's a good idea to randomise the weather because it can lead to extreme situations (e.g. dense fog with zero visibility). So we'd have to include limits to each weather element and at that point it'd be easier to call the commands one-by-one like in the example, instead of bundling them in one function.

My other concern is the performance as force-changing the weather mid-mission hangs the game while the weather is synced between server and clients.

**Comment by kMaN175** [comment]
You are probably correct. Thank you for responding!
